*---------------------------
* Bias current
*---------------------------
.param Ibias=44u

*---------------------------
* Transistor dimensions
*---------------------------
.param W1=275u
.param L1=1.05u
.param W2=275u
.param L2=1.05u

.param W3=62.8u
.param L3=10.05u
.param W4=62.8u
.param L4=10.05u

.param W5=37u
.param L5=1.05u
.param W6=37u
.param L6=1.05u

.param W7=18.2u
.param L7=1.05u
.param W8=37u
.param L8=1.05u

*---------------------------
* Compensation network
*---------------------------
.param Rc=4.7k
.param Cc=620p

*---------------------------
* Feedback network
*---------------------------
.param Cf=150f
.param Cin=15p
.param Rf=8T
